/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import model.User;

/**
 *
 * @author NgocTram
 */
public class MainForm extends javax.swing.JFrame {

    private LoginDialog loginDialog;
    private User user;
    private ChangePasswordFrame changePasswordFrame;
    private PersonalAccountUpdate personalAccountUpdate;
    private StaffManagementPanel mStaffPanel;
    private UserManagementPanel mUserPanel;
    private AboutUsDialog aboutDialog;

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        setLocationRelativeTo(null);
    }

    public MainForm(User nd) {
        initComponents();
        setLocationRelativeTo(null);
        lblUsername.setText(nd.getTen());
        lblVaitro.setText(nd.getVaiTro());
        user = nd;
        if (nd.getVaiTro().equals("Tổng quản lý")) {
            hienThiQLND();
            hienThiQLNV();
        }
        if (nd.getVaiTro().equals("Quản lý nhân viên")) {
            hienThiQLNV();
            menuQLND.setEnabled(false);
            qlnd.setEnabled(false);
        }
    }

    public void hienThiQLNV() {
        if (mStaffPanel == null) {
            mStaffPanel = new StaffManagementPanel();
            ImageIcon icon = new ImageIcon(getClass()
                    .getResource("/icons/Person-Male-Light-icon-16.png"));

            tplMainBoard.addTab("Quản lý nhân viên", icon, mStaffPanel, "Quản lý nhân viên");
        }
        tplMainBoard.setSelectedComponent(mStaffPanel);
    }

    public void hienThiQLND() {
        if (mUserPanel == null) {
            mUserPanel = new UserManagementPanel();
            ImageIcon icon = new ImageIcon(getClass()
                    .getResource("/icons/open-file-icon-16.png"));

            tplMainBoard.addTab("Quản lý người dùng", icon, mUserPanel, "Quản lý người dùng");
        }
        tplMainBoard.setSelectedComponent(mUserPanel);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        qlnv = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        qlcc = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        qlnd = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblVaitro = new javax.swing.JLabel();
        btnChangePwd = new javax.swing.JButton();
        Logout = new javax.swing.JButton();
        tplMainBoard = new javax.swing.JTabbedPane();
        btnUpdate = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuLogout = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        Exit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuQLNV = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem4 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        menuQLND = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuAboutus = new javax.swing.JMenuItem();
        menuAboutSystem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jToolBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jToolBar1.setRollover(true);
        jToolBar1.setAlignmentX(0.0F);

        qlnv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Person-Male-Light-icon-48.png"))); // NOI18N
        qlnv.setText("Quản lý nhân viên");
        qlnv.setFocusable(false);
        qlnv.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        qlnv.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        qlnv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qlnvActionPerformed(evt);
            }
        });
        jToolBar1.add(qlnv);
        jToolBar1.add(jSeparator4);

        qlcc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Actions-document-edit-icon-48.png"))); // NOI18N
        qlcc.setText("Quản lý chấm công");
        qlcc.setFocusable(false);
        qlcc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        qlcc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(qlcc);
        jToolBar1.add(jSeparator5);

        qlnd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/open-file-icon-48.png"))); // NOI18N
        qlnd.setText("Quản lý người dùng");
        qlnd.setFocusable(false);
        qlnd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        qlnd.setMaximumSize(new java.awt.Dimension(117, 90));
        qlnd.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        qlnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qlndActionPerformed(evt);
            }
        });
        jToolBar1.add(qlnd);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Xin chào,");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Quyền: ");

        btnChangePwd.setText("Đổi mật khẩu");
        btnChangePwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePwdActionPerformed(evt);
            }
        });

        Logout.setText("Đăng xuất");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });

        btnUpdate.setText("Cập nhật tài khoản");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        jMenu1.setText("Hệ thống");

        menuLogout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Login-icon-16.png"))); // NOI18N
        menuLogout.setText("Đăng xuất");
        menuLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLogoutActionPerformed(evt);
            }
        });
        jMenu1.add(menuLogout);
        jMenu1.add(jSeparator2);

        Exit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Actions-edit-delete-icon-16.png"))); // NOI18N
        Exit.setText("Thoát");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        jMenu1.add(Exit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Quản lý");

        menuQLNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Person-Male-Light-icon-16.png"))); // NOI18N
        menuQLNV.setText("Quản lý nhân viên");
        menuQLNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuQLNVActionPerformed(evt);
            }
        });
        jMenu2.add(menuQLNV);
        jMenu2.add(jSeparator1);

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Actions-document-edit-icon-16.png"))); // NOI18N
        jMenuItem4.setText("Quản lý chấm công");
        jMenu2.add(jMenuItem4);
        jMenu2.add(jSeparator3);

        menuQLND.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/gpa-icon.png"))); // NOI18N
        menuQLND.setText("Quản lý người dùng");
        menuQLND.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuQLNDActionPerformed(evt);
            }
        });
        jMenu2.add(menuQLND);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Help");

        menuAboutus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Help-icon-16.png"))); // NOI18N
        menuAboutus.setText("Liên hệ");
        menuAboutus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAboutusActionPerformed(evt);
            }
        });
        jMenu3.add(menuAboutus);

        menuAboutSystem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Actions-help-about-icon-16.png"))); // NOI18N
        menuAboutSystem.setText("Giới thiệu");
        menuAboutSystem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAboutSystemActionPerformed(evt);
            }
        });
        jMenu3.add(menuAboutSystem);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblUsername))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblVaitro)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnChangePwd)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdate)
                        .addGap(18, 18, 18)
                        .addComponent(Logout)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addComponent(tplMainBoard)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(lblUsername))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lblVaitro))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnChangePwd)
                            .addComponent(Logout)
                            .addComponent(btnUpdate)))
                    .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tplMainBoard, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuQLNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuQLNVActionPerformed
        hienThiQLNV();
    }//GEN-LAST:event_menuQLNVActionPerformed

    private void qlndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qlndActionPerformed
        hienThiQLND();
    }//GEN-LAST:event_qlndActionPerformed

    private void qlnvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qlnvActionPerformed
        hienThiQLNV();
    }//GEN-LAST:event_qlnvActionPerformed

    private void btnChangePwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePwdActionPerformed
        if (changePasswordFrame == null) {
            changePasswordFrame = new ChangePasswordFrame(this, user);
        }
        changePasswordFrame.setVisible(true);
        this.setEnabled(false);
    }//GEN-LAST:event_btnChangePwdActionPerformed

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        int ok = JOptionPane.showConfirmDialog(this, "Bạn có thật sự muốn đăng xuất không?",
                "Đăng xuất", JOptionPane.YES_NO_OPTION);
        if (ok == JOptionPane.YES_OPTION) {
            if (loginDialog == null) {
                loginDialog = new LoginDialog();
            }
            this.dispose();
            loginDialog.setVisible(true);
        }
    }//GEN-LAST:event_LogoutActionPerformed

    private void menuLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLogoutActionPerformed
        LogoutActionPerformed(evt);
    }//GEN-LAST:event_menuLogoutActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ExitActionPerformed

    private void menuAboutSystemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAboutSystemActionPerformed
        String s = new String();
        s = "Hệ thống được thiết kế để có thể dễ dàng làm các công việc sau: \n"
                + "- Quản lý thông tin của nhân viên.\n"
                + "- Quản lý chấm công cho nhân viên theo từng ngày cụ thể.\n"
                + "- Tính lương chi trả cho nhân viên khi đến tháng trả lương.\n"
                + "- Quản lý người dùng hệ thống.";
        JOptionPane.showMessageDialog(this, s, "Nội dung", JOptionPane.DEFAULT_OPTION);
    }//GEN-LAST:event_menuAboutSystemActionPerformed

    private void menuAboutusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAboutusActionPerformed
        if (aboutDialog == null) {
            aboutDialog = new AboutUsDialog(this);
        }
        aboutDialog.setVisible(true);
        this.setEnabled(false);
    }//GEN-LAST:event_menuAboutusActionPerformed

    private void menuQLNDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuQLNDActionPerformed
        hienThiQLND();
    }//GEN-LAST:event_menuQLNDActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        if (personalAccountUpdate == null) {
            personalAccountUpdate = new PersonalAccountUpdate(this, user);
        }
        personalAccountUpdate.setVisible(true);
        this.setEnabled(false);
    }//GEN-LAST:event_btnUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Exit;
    private javax.swing.JButton Logout;
    private javax.swing.JButton btnChangePwd;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lblVaitro;
    private javax.swing.JMenuItem menuAboutSystem;
    private javax.swing.JMenuItem menuAboutus;
    private javax.swing.JMenuItem menuLogout;
    private javax.swing.JMenuItem menuQLND;
    private javax.swing.JMenuItem menuQLNV;
    private javax.swing.JButton qlcc;
    private javax.swing.JButton qlnd;
    private javax.swing.JButton qlnv;
    private javax.swing.JTabbedPane tplMainBoard;
    // End of variables declaration//GEN-END:variables
}
