/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import manage.NhanVienManage;
import model.NhanVien;

/**
 *
 * @author NgocTram
 */
public class StaffManagementPanel extends javax.swing.JPanel {

   DefaultTableModel tblModel;

    public StaffManagementPanel() {
        initComponents();
        initTable();
        loadDataToTable();
        btnUpdate.setEnabled(false);
        btnDelete.setEnabled(false);

    }
    private void initTable() {
        tblModel = new DefaultTableModel();
        tblModel.setColumnIdentifiers(new String [] {"Mã nhân viên","Họ tên","Lương (K/giờ)",
        "Email","Số ĐT", "Giới tính","Địa chỉ"});
        tblNhanVien.setModel(tblModel);
    }
    private void loadDataToTable() {
        try {
            NhanVienManage ql = new NhanVienManage();
            List <NhanVien> list = ql.findAll();
            tblModel.setRowCount(0);
            for (NhanVien nv:list) {
                tblModel.addRow(new Object[] {nv.getMaNV(),nv.getHoten(),nv.getLuong(),
                nv.getEmail(),nv.getSdt(),nv.getGioiTinh(),nv.getDiachi()});
            }
            tblModel.fireTableDataChanged();
        }catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    public boolean isRong(String s) {
        return (s.equals(""));
        
    }
     
    public boolean isNumber(String s) {
        int length = s.length();
        int i;
        for (i=0; i<length; i++) {
            if (s.charAt(i) < '0' || s.charAt(i)> '9' ) return false;
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtMaNhanVien = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtSalary = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnNam = new javax.swing.JRadioButton();
        btnNu = new javax.swing.JRadioButton();
        txtPhone = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        btnNew = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblNhanVien = new javax.swing.JTable();

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 0));
        jLabel1.setText("QUẢN LÝ NHÂN VIÊN");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel2.setText("Mã nhân viên");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel3.setText("Họ và Tên");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel4.setText("Tiền Lương");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel5.setText("Giới tính");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel6.setText("Email");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel7.setText("Số Điện Thoại");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel8.setText("Địa Chỉ");

        txtSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSalaryActionPerformed(evt);
            }
        });

        jLabel9.setText("Nghìn đồng/Giờ");

        buttonGroup1.add(btnNam);
        btnNam.setSelected(true);
        btnNam.setText("Nam");

        buttonGroup1.add(btnNu);
        btnNu.setText("Nữ");

        txtAddress.setColumns(20);
        txtAddress.setRows(5);
        jScrollPane1.setViewportView(txtAddress);

        btnNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/new-icon-16.png"))); // NOI18N
        btnNew.setText("Nhập mới");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Actions-document-edit-icon-16.png"))); // NOI18N
        btnUpdate.setText("Cập nhật");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Actions-edit-delete-icon-16.png"))); // NOI18N
        btnDelete.setText("Xóa");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Save-icon.png"))); // NOI18N
        btnSave.setText("Lưu");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNew, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNew)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addComponent(btnUpdate)
                .addGap(18, 18, 18)
                .addComponent(btnDelete)
                .addGap(18, 18, 18)
                .addComponent(btnSave)
                .addGap(18, 18, 18))
        );

        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        tblNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblNhanVien.setMinimumSize(new java.awt.Dimension(100, 120));
        tblNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNhanVienMouseClicked(evt);
            }
        });
        tblNhanVien.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblNhanVienKeyReleased(evt);
            }
        });
        jScrollPane4.setViewportView(tblNhanVien);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel3))
                                        .addGap(31, 31, 31)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(txtSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jLabel9))
                                                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(47, 47, 47)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btnNam)
                                                .addGap(22, 22, 22)
                                                .addComponent(btnNu))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(14, 14, 14)
                                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 675, Short.MAX_VALUE))
                                .addGap(73, 73, 73))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(2, 2, 2)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(btnNam)
                            .addComponent(btnNu))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSalaryActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        txtName.setText("");
        txtPhone.setText("");
        txtEmail.setText("");
        txtSalary.setText("");
        txtAddress.setText("");
        txtMaNhanVien.setText("");
        txtMaNhanVien.requestFocus();
        btnSave.setEnabled(true);
        txtMaNhanVien.setEnabled(true);
        btnUpdate.setEnabled(false);
        btnDelete.setEnabled(false);
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        int loi = 0;
        if (txtAddress.getText().equals("")) {
            loi = 1;
            txtAddress.requestFocus();
        }
        if (txtPhone.getText().equals("")) {
            loi = 1;
            txtPhone.requestFocus();
        }
        if (txtEmail.getText().equals("")) {
            loi = 1;
            txtEmail.requestFocus();
        }
        if (txtSalary.getText().equals("")) {
            loi = 1;
            txtSalary.requestFocus();
        }
        if (txtName.getText().equals("")) {
            loi = 1;
            txtName.requestFocus();
        }
        if (txtMaNhanVien.getText().equals("")) {
            loi = 1;
            txtMaNhanVien.requestFocus();
        }
        if (loi == 1) JOptionPane.showMessageDialog(this, "Không được để trống trường dữ liệu nào!",
            "Lỗi!", JOptionPane.ERROR_MESSAGE);
        if (!isNumber(txtPhone.getText()) || txtPhone.getText().length()<9) {
            loi=2;
            JOptionPane.showMessageDialog(this, "Số điện thoại không hợp lệ!",
                "Lỗi!", JOptionPane.ERROR_MESSAGE);
        }
        if (loi == 0) {
            try {
                NhanVien nv = new NhanVien();
                nv.setDiachi(txtAddress.getText());
                nv.setEmail(txtEmail.getText());
                nv.setHoten(txtName.getText());
                nv.setLuong(txtSalary.getText());
                nv.setMaNV(txtMaNhanVien.getText());
                nv.setSdt(txtPhone.getText());
                nv.setGioiTinh(btnNam.isSelected()? "Nam":"Nữ");
                NhanVienManage ql = new NhanVienManage();
                int ok = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn cập nhật không?",
                    "Hỏi?", JOptionPane.YES_NO_OPTION);
                if (ok != JOptionPane.YES_OPTION) {
                    return;
                }
                if (ql.update(nv)) {
                    loadDataToTable();
                    JOptionPane.showMessageDialog(this, "Cập nhật thành công!",
                        "Thông báo!", JOptionPane.INFORMATION_MESSAGE);
                    btnNewActionPerformed(evt);

                }
                else {
                    JOptionPane.showMessageDialog(this, "Không tồn tại mã nhân viên này!",
                        "Lỗi!", JOptionPane.ERROR_MESSAGE);
                }

            } catch(Exception e) {
                JOptionPane.showMessageDialog(this, "Không tồn tại mã nhân viên này!",
                    "Lỗi!", JOptionPane.ERROR_MESSAGE);
                //e.printStackTrace();
            }
            btnNewActionPerformed(evt);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int loi = 0;
        if (txtMaNhanVien.getText().equals("")) {
            loi = 1;
            txtMaNhanVien.requestFocus();
        }
        if (loi == 1) JOptionPane.showMessageDialog(this, "Bạn chưa nhập mã nhân viên!",
            "Lỗi!", JOptionPane.ERROR_MESSAGE);

        if (loi == 0) {
            try {
                NhanVienManage ql = new NhanVienManage();
                int ok = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xóa nhân viên có mã "
                    + txtMaNhanVien.getText()+" không?!",
                    "Hỏi?", JOptionPane.YES_NO_OPTION);
                if (ok != JOptionPane.YES_OPTION) {
                    return;
                }
                if (ql.delete(txtMaNhanVien.getText())) {
                    loadDataToTable();
                    JOptionPane.showMessageDialog(this, "Xóa thành công!",
                        "Thông báo!", JOptionPane.INFORMATION_MESSAGE);

                }
                else {
                    JOptionPane.showMessageDialog(this, "Không tồn tại mã nhân viên này!",
                        "Lỗi!", JOptionPane.ERROR_MESSAGE);
                }

            } catch(Exception e) {
                JOptionPane.showMessageDialog(this, "Không tồn tại mã nhân viên này!",
                    "Lỗi!", JOptionPane.ERROR_MESSAGE);
                //e.printStackTrace();
            }
            btnNewActionPerformed(evt);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed
    
    private boolean checkEmail(String s) {
        int o=-1;
        int dem=0;
        for (int i=0; i<s.length(); i++ ) {
            if (s.charAt(i)=='@') {
                dem++;
                o=i; 
            }      
        }
        if (dem>1) return false;
        if (o<=0) return false;
        if (o>=(s.length()-4)) return false;
        return true;
    }
    
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        int loi = 0;
        if (txtAddress.getText().equals("")) {
            loi = 1;
            txtAddress.requestFocus();
        }
        if (txtPhone.getText().equals("")) {
            loi = 1;
            txtPhone.requestFocus();
        }
        if (txtEmail.getText().equals("")) {
            loi = 1;
            txtEmail.requestFocus();
        }
        if (txtSalary.getText().equals("")) {
            loi = 1;
            txtSalary.requestFocus();
        }
        if (txtName.getText().equals("")) {
            loi = 1;
            txtName.requestFocus();
        }
        if (txtMaNhanVien.getText().equals("")) {
            loi = 1;
            txtMaNhanVien.requestFocus();
        }
        if (loi == 1) {
            JOptionPane.showMessageDialog(this, "Không được để trống trường dữ liệu nào!",
                "Lỗi!", JOptionPane.ERROR_MESSAGE);
            return; }
        try {
            float luong = Float.parseFloat(txtSalary.getText());

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Bạn phải nhập 'Lương' đúng định dạng! (VD: 12.5 hoặc 13)",
                "Lỗi!", JOptionPane.ERROR_MESSAGE);
            txtSalary.requestFocus();
            return;
        }
        if (!checkEmail(txtEmail.getText())) {
            loi=2;
            JOptionPane.showMessageDialog(this, "Email không hợp lệ!",
                "Lỗi!", JOptionPane.ERROR_MESSAGE);
            txtEmail.requestFocus();
            return;
        }
        if (!isNumber(txtPhone.getText())|| txtPhone.getText().length()<9) {
            loi=2;
            JOptionPane.showMessageDialog(this, "Số điện thoại không hợp lệ!",
                "Lỗi!", JOptionPane.ERROR_MESSAGE);
            txtPhone.requestFocus();
            return;
        }

        if (loi == 0) {
            try {
                NhanVien nv = new NhanVien();
                nv.setDiachi(txtAddress.getText());
                nv.setEmail(txtEmail.getText());
                nv.setHoten(txtName.getText());
                nv.setLuong(txtSalary.getText());
                nv.setMaNV(txtMaNhanVien.getText());
                nv.setSdt(txtPhone.getText());
                nv.setGioiTinh(btnNam.isSelected()? "Nam":"Nữ");
                NhanVienManage ql = new NhanVienManage();
                if (ql.insert(nv)) {
                    loadDataToTable();
                    JOptionPane.showMessageDialog(this, "Lưu thành công!",
                        "Thông báo!", JOptionPane.INFORMATION_MESSAGE);

                }
                else {
                    JOptionPane.showMessageDialog(this, "Mã nhân viên đã được lưu trước đó!",
                        "Lỗi!", JOptionPane.ERROR_MESSAGE);
                }

            } catch(Exception e) {
                JOptionPane.showMessageDialog(this, "Mã nhân viên đã được lưu trước đó!",
                    "Lỗi!", JOptionPane.ERROR_MESSAGE);
                //e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void tblNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNhanVienMouseClicked
        try {
            int row = tblNhanVien.getSelectedRow();
            if (row>=0) {
                String id = (String) tblNhanVien.getValueAt(row,0);
                NhanVienManage ql = new NhanVienManage();
                NhanVien nv = ql.findByMaNV(id);
                if (nv != null) {
                    btnDelete.setEnabled(true);
                    btnUpdate.setEnabled(true);
                    txtMaNhanVien.setEnabled(false);
                    btnSave.setEnabled(false);
                    txtName.setText(nv.getHoten());
                    txtPhone.setText(nv.getSdt());
                    txtEmail.setText(nv.getEmail());
                    txtSalary.setText(nv.getLuong());
                    txtAddress.setText(nv.getDiachi());
                    txtMaNhanVien.setText(nv.getMaNV());
                    if (nv.getGioiTinh().equalsIgnoreCase("nam")) btnNam.setSelected(true);
                    else btnNu.setSelected(true);

                }
            }
        }catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_tblNhanVienMouseClicked

    private void tblNhanVienKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblNhanVienKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_UP ||
            evt.getKeyCode() == KeyEvent.VK_DOWN) {
            try {
                int row = tblNhanVien.getSelectedRow();
                if (row>=0) {
                    String id = (String) tblNhanVien.getValueAt(row,0);
                    NhanVienManage ql = new NhanVienManage();
                    NhanVien nv = ql.findByMaNV(id);
                    if (nv != null) {
                        btnDelete.setEnabled(true);
                        btnUpdate.setEnabled(true);
                        txtMaNhanVien.setEnabled(false);
                        btnSave.setEnabled(false);
                        txtName.setText(nv.getHoten());
                        txtPhone.setText(nv.getSdt());
                        txtEmail.setText(nv.getEmail());
                        txtSalary.setText(nv.getLuong());
                        txtAddress.setText(nv.getDiachi());
                        txtMaNhanVien.setText(nv.getMaNV());
                        if (nv.getGioiTinh().equalsIgnoreCase("nam")) btnNam.setSelected(true);
                        else btnNu.setSelected(true);
                    }
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        };
    }//GEN-LAST:event_tblNhanVienKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JRadioButton btnNam;
    private javax.swing.JButton btnNew;
    private javax.swing.JRadioButton btnNu;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable tblNhanVien;
    private javax.swing.JTextArea txtAddress;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtMaNhanVien;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtSalary;
    // End of variables declaration//GEN-END:variables
}
